2024-10-27 13:36:29,091 - ERROR - An error occurred: Can't get attribute 'Config' on <module '__main__' from 'C:\\Users\\Ayush\\OneDrive\\Desktop\\ai-ml_project\\cbt_model.py'>
2024-10-27 13:37:32,909 - ERROR - An error occurred: Can't get attribute 'Config' on <module '__main__' from 'C:\\Users\\Ayush\\OneDrive\\Desktop\\ai-ml_project\\cbt_model.py'>
